
PROMPT--*****************SEQUENCES***********************
DROP SEQUENCE SEQ_DOMINO;
DROP SEQUENCE SEQ_GAME_ATTENDEE;
DROP SEQUENCE SEQ_USER;
DROP SEQUENCE SEQ_GAME;
--SEQUENCES
CREATE SEQUENCE SEQ_DOMINO MINVALUE 1 MAXVALUE 36 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USER MINVALUE 1 MAXVALUE 99999999999 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GAME MINVALUE 1 MAXVALUE 99999999999 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GAME_ATTENDEE MINVALUE 1 MAXVALUE 99999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT--*****************TABLES***********************
--TABLES
DROP TABLE T_GAME_USER_DOMINOS;
DROP TABLE T_GAME_PROGRESS;
DROP TABLE T_GAME_RESULTS;
DROP TABLE T_GAMES_ATTENDEES;
DROP TABLE T_GAMES;
DROP TABLE T_DOMINOS;
DROP TABLE T_ACCOUNTS;
DROP TABLE T_USERS;

CREATE TABLE T_DOMINOS(
  DOMINO_ID NUMBER(10,0) DEFAULT SEQ_DOMINO.NEXTVAL NOT NULL,
  DOMINO_LEFT_PIECE NUMBER(1,0) NOT NULL,
  DOMINO_RIGHT_PIECE NUMBER(1,0) NOT NULL,
  CONSTRAINT DOMINO_ID_PK PRIMARY KEY (DOMINO_ID),
  CONSTRAINT DOMINO_VALUE_UNIQUE UNIQUE (DOMINO_LEFT_PIECE,DOMINO_RIGHT_PIECE),
  CONSTRAINT DOMINO_LEFT_PIECE_CHECK CHECK (DOMINO_LEFT_PIECE BETWEEN 0 AND 6),
  CONSTRAINT DOMINO_RIGHT_PIECE_CHECK CHECK (DOMINO_RIGHT_PIECE BETWEEN 0 AND 6)
);

CREATE TABLE T_USERS(
    USER_ID NUMBER(10,0) DEFAULT SEQ_USER.NEXTVAL NOT NULL,
    USER_FIRST_NAME VARCHAR(75) NOT NULL,
    USER_LAST_NAME VARCHAR(75) NOT NULL,
    USER_MIDDLE_NAME VARCHAR(75) NULL,
    USER_DATE_OF_BIRTH DATE NOT NULL,
    USER_GENDER VARCHAR(1) NOT NULL,
    CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID),
    CONSTRAINT USER_UNIQUE UNIQUE (USER_FIRST_NAME,USER_LAST_NAME, USER_MIDDLE_NAME, USER_DATE_OF_BIRTH, USER_GENDER),
    CONSTRAINT USER_GENDER_CHECK CHECK (USER_GENDER IN('F','M'))
);

CREATE TABLE T_ACCOUNTS(
    ACCOUNT_USER_ID NUMBER(10,0) NOT NULL,
    ACCOUNT_USERNAME VARCHAR(50) NOT NULL,
    ACCOUNT_PASSWORD VARCHAR(256) NOT NULL,
    CONSTRAINT T_A_ACCOUNT_USER_ID_FK FOREIGN KEY (ACCOUNT_USER_ID) REFERENCES T_USERS(USER_ID),
    CONSTRAINT USER_ACCOUNT_UNIQUE UNIQUE (ACCOUNT_USER_ID,ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
);

CREATE TABLE T_GAMES(
  GAME_ID NUMBER(10,0) DEFAULT SEQ_GAME.NEXTVAL NOT NULL,
  GAME_NAME VARCHAR(50) NOT NULL,
  CREATED_BY_USER_ID NUMBER(10,0) NOT NULL,
  CREATED_TIMESTAMP DATE NOT NULL,
  START_TIMESTAMP DATE NULL,
  END_TIMESTAMP DATE NULL,
  CONSTRAINT GAME_ID_PK PRIMARY KEY (GAME_ID),
  CONSTRAINT GAME_NAME_UNIQUE UNIQUE (GAME_NAME),
  CONSTRAINT T_G_CREATED_BY_USER_ID_FK FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES T_USERS(USER_ID)
);

CREATE TABLE T_GAMES_ATTENDEES(
  GAME_ATTENDEE_ID NUMBER(10,0) DEFAULT SEQ_GAME_ATTENDEE.NEXTVAL NOT NULL,
  GAME_ID NUMBER(10,0) NOT NULL,
  USER_ID NUMBER(10,0) NOT NULL,
  CONSTRAINT GAME_ATTENDEE_ID_PK PRIMARY KEY (GAME_ATTENDEE_ID),
  CONSTRAINT T_GT_GAME_ID_FK FOREIGN KEY (GAME_ID) REFERENCES T_GAMES(GAME_ID),
  CONSTRAINT T_GT_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES T_USERS(USER_ID)
);

CREATE TABLE T_GAME_RESULTS(
  GAME_ATTENDEE_ID NUMBER(10,0) NOT NULL,
  COUNT_OF_SCORES NUMBER(3,0) NOT NULL,
  CONSTRAINT T_GR_GAME_ATTENDEE_ID_FK FOREIGN KEY (GAME_ATTENDEE_ID) REFERENCES T_GAMES_ATTENDEES(GAME_ATTENDEE_ID)
);

CREATE TABLE T_GAME_PROGRESS(
  GAME_ATTENDEE_ID NUMBER(10,0) NOT NULL,
  GAME_PROGRESS_TIMESTAMP DATE NOT NULL,
  DOMINO_ID NUMBER(10,0) NOT NULL,
  CONSTRAINT T_GP_GAME_ATTENDEE_ID_FK FOREIGN KEY (GAME_ATTENDEE_ID) REFERENCES T_GAMES_ATTENDEES(GAME_ATTENDEE_ID),
  CONSTRAINT T_GP_DOMINO_ID_FK FOREIGN KEY (DOMINO_ID) REFERENCES T_DOMINOS(DOMINO_ID)
);

CREATE TABLE T_GAME_USER_DOMINOS(
  GAME_ATTENDEE_ID NUMBER(10,0) NOT NULL,
  DOMINO_ID NUMBER(10,0) NOT NULL,
  CONSTRAINT T_GUD_GAME_ATTENDEE_ID_FK FOREIGN KEY (GAME_ATTENDEE_ID) REFERENCES T_GAMES_ATTENDEES(GAME_ATTENDEE_ID),
  CONSTRAINT T_GUD_DOMINO_ID_FK FOREIGN KEY (DOMINO_ID) REFERENCES T_DOMINOS(DOMINO_ID)
);

PROMPT--*****************VIEWS***********************
--VIEWS
DROP VIEW V_DOMINOS;
CREATE OR REPLACE VIEW V_DOMINOS AS
  SELECT * FROM T_DOMINOS;
  
PROMPT--*****************MATERIALIZED VIEWS***********************
--MATERIALIZED VIEWS
DROP MATERIALIZED VIEW MV_DOMINOS;
CREATE MATERIALIZED VIEW MV_DOMINOS
BUILD IMMEDIATE
REFRESH
COMPLETE
ON COMMIT
AS
  SELECT * FROM T_DOMINOS;
  
