
PROMPT--*****************SEQUENCES***********************
DROP SEQUENCE SEQ_DOMINO;
--SEQUENCES
CREATE SEQUENCE SEQ_DOMINO MINVALUE 1 MAXVALUE 36 START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT--*****************TABLES***********************
--TABLES
DROP TABLE T_DOMINO;
CREATE TABLE T_DOMINO(
  DOMINO_ID NUMBER(10,0) DEFAULT SEQ_DOMINO.NEXTVAL NOT NULL,
  DOMINO_LEFT_PIECE NUMBER(1,0) NOT NULL,
  DOMINO_RIGHT_PIECE NUMBER(1,0) NOT NULL,
  CONSTRAINT DOMINO_ID_PK PRIMARY KEY (DOMINO_ID),
  CONSTRAINT DOMINO_VALUE_UNIQUE UNIQUE (DOMINO_LEFT_PIECE,DOMINO_RIGHT_PIECE)
);

PROMPT--*****************VIEWS***********************
--VIEWS
DROP VIEW V_DOMINO;
CREATE OR REPLACE VIEW V_DOMINO AS
  SELECT * FROM T_DOMINO;
  
PROMPT--*****************MATERIALIZED VIEWS***********************
--MATERIALIZED VIEWS
DROP MATERIALIZED VIEW MV_DOMINO;
CREATE MATERIALIZED VIEW MV_DOMINO
BUILD IMMEDIATE
REFRESH
COMPLETE
ON COMMIT
AS
  SELECT * FROM T_DOMINO;
  
PROMPT--*****************PROCEDURES***********************
--PROCEDURES
DROP PROCEDURE INSERT_DOMINO;
CREATE OR REPLACE PROCEDURE INSERT_DOMINO(
DOMINO_LEFT_PIECE_IN IN T_DOMINO.DOMINO_LEFT_PIECE%TYPE, 
DOMINO_RIGHT_PIECE_IN IN T_DOMINO.DOMINO_RIGHT_PIECE%TYPE) IS
BEGIN
  INSERT INTO T_DOMINO(DOMINO_LEFT_PIECE, DOMINO_RIGHT_PIECE) 
  VALUES(DOMINO_LEFT_PIECE_IN, DOMINO_RIGHT_PIECE_IN);
  COMMIT;
END;

DROP PROCEDURE FILL_INSERT_DOMINO;
CREATE OR REPLACE PROCEDURE FILL_INSERT_DOMINO 
IS
  START_NUMBER NUMBER := 0;
  START_NUMBER_INNER NUMBER := 0;
  END_NUMBER NUMBER := 6;
BEGIN
  WHILE START_NUMBER <= END_NUMBER
  LOOP
    START_NUMBER_INNER := START_NUMBER;
    WHILE START_NUMBER_INNER <= END_NUMBER
    LOOP
      INSERT INTO T_DOMINO(DOMINO_LEFT_PIECE, DOMINO_RIGHT_PIECE) 
      VALUES(START_NUMBER, START_NUMBER_INNER);
      COMMIT;
      DBMS_OUTPUT.PUT_LINE(START_NUMBER || '|' || START_NUMBER_INNER);
      START_NUMBER_INNER := START_NUMBER_INNER + 1;
    END LOOP;
    START_NUMBER := START_NUMBER + 1;
  END LOOP;
END;

PROMPT--*****************FUNCTIONS***********************
--FUNCTIONS
DROP FUNCTION FILL_DOMINO;
CREATE OR REPLACE FUNCTION FILL_DOMINO RETURN NUMBER
IS
  COUNT_DOMINO NUMBER := 0;
  START_NUMBER NUMBER := 0;
  START_NUMBER_INNER NUMBER := 0;
  END_NUMBER NUMBER := 6;
BEGIN
  WHILE START_NUMBER <= END_NUMBER
  LOOP
    START_NUMBER_INNER := START_NUMBER;
    WHILE START_NUMBER_INNER <= END_NUMBER
    LOOP
      DBMS_OUTPUT.PUT_LINE(START_NUMBER || '|' || START_NUMBER_INNER);
      COUNT_DOMINO := COUNT_DOMINO + 1;
      START_NUMBER_INNER := START_NUMBER_INNER + 1;
    END LOOP;
    START_NUMBER := START_NUMBER + 1;
  END LOOP;
  RETURN COUNT_DOMINO;
END;

SET SERVEROUTPUT ON;
DECLARE
  RETURN_COUNT NUMBER;
BEGIN
  FILL_INSERT_DOMINO;
END;
