PROMPT--*****************PROCEDURES***********************
--PROCEDURES
DROP PROCEDURE INSERT_DOMINO;
CREATE OR REPLACE PROCEDURE INSERT_DOMINO(
DOMINO_LEFT_PIECE_IN IN T_DOMINOS.DOMINO_LEFT_PIECE%TYPE, 
DOMINO_RIGHT_PIECE_IN IN T_DOMINOS.DOMINO_RIGHT_PIECE%TYPE) IS
BEGIN
  INSERT INTO T_DOMINOS(DOMINO_LEFT_PIECE, DOMINO_RIGHT_PIECE) 
  VALUES(DOMINO_LEFT_PIECE_IN, DOMINO_RIGHT_PIECE_IN);
  COMMIT;
END;
/

DROP PROCEDURE FILL_INSERT_DOMINO;
CREATE OR REPLACE PROCEDURE FILL_INSERT_DOMINO 
IS
  START_NUMBER NUMBER := 0;
  START_NUMBER_INNER NUMBER := 0;
  END_NUMBER NUMBER := 6;
BEGIN
  WHILE START_NUMBER <= END_NUMBER
  LOOP
    START_NUMBER_INNER := START_NUMBER;
    WHILE START_NUMBER_INNER <= END_NUMBER
    LOOP
      INSERT INTO T_DOMINOS(DOMINO_LEFT_PIECE, DOMINO_RIGHT_PIECE) 
      VALUES(START_NUMBER, START_NUMBER_INNER);
      COMMIT;
      DBMS_OUTPUT.PUT_LINE(START_NUMBER || '|' || START_NUMBER_INNER);
      START_NUMBER_INNER := START_NUMBER_INNER + 1;
    END LOOP;
    START_NUMBER := START_NUMBER + 1;
  END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE PACKAGE_OP(OPERATION_IN IN INTEGER)
AS
  TYPE PACKAGE_NAME_ARRAY IS VARRAY(25) OF VARCHAR2(30);
  PACKAGE_ARRAY PACKAGE_NAME_ARRAY;
  CUR_COUNT INTEGER;
  TEMP_VAL VARCHAR(250);
BEGIN
  PACKAGE_ARRAY := PACKAGE_NAME_ARRAY('PKG_COMMON', 'PKG_DOMINOS_DOMINOS', 'PKG_DOMINOS_USERS', 
                    'PKG_DOMINOS_ACCOUNTS', 'PKG_DOMINOS_GAMES', 'PKG_DOMINOS_GAMES_ATTENDEES', 
                    'PKG_DOMINOS_GAME_USER_DOMINOS');
  CUR_COUNT := PACKAGE_ARRAY.COUNT;
  DBMS_OUTPUT.PUT_LINE('PACKAGE COUNT - ' || CUR_COUNT);
  
  FOR I IN 1 .. CUR_COUNT LOOP
    IF OPERATION_IN = 0 THEN
      EXECUTE IMMEDIATE 'DROP PACKAGE ' || PACKAGE_ARRAY(I);
    ELSIF OPERATION_IN = 1 THEN
      TEMP_VAL := 'ALTER PACKAGE ' || PACKAGE_ARRAY(I) || ' COMPILE';
      DBMS_OUTPUT.PUT_LINE(TEMP_VAL);
      EXECUTE IMMEDIATE TEMP_VAL;
      TEMP_VAL := TEMP_VAL || ' BODY';
      EXECUTE IMMEDIATE TEMP_VAL;
      DBMS_OUTPUT.PUT_LINE(TEMP_VAL);
    END IF;
  END LOOP;
  
END PACKAGE_OP;
/

PROMPT--*****************FUNCTIONS***********************
--FUNCTIONS
DROP FUNCTION FILL_DOMINO_TEST;
CREATE OR REPLACE FUNCTION FILL_DOMINO_TEST RETURN NUMBER
IS
  COUNT_DOMINO NUMBER := 0;
  START_NUMBER NUMBER := 0;
  START_NUMBER_INNER NUMBER := 0;
  END_NUMBER NUMBER := 6;
BEGIN
  WHILE START_NUMBER <= END_NUMBER
  LOOP
    START_NUMBER_INNER := START_NUMBER;
    WHILE START_NUMBER_INNER <= END_NUMBER
    LOOP
      DBMS_OUTPUT.PUT_LINE(START_NUMBER || '|' || START_NUMBER_INNER);
      COUNT_DOMINO := COUNT_DOMINO + 1;
      START_NUMBER_INNER := START_NUMBER_INNER + 1;
    END LOOP;
    START_NUMBER := START_NUMBER + 1;
  END LOOP;
  RETURN COUNT_DOMINO;
END;
/
