CREATE OR REPLACE PACKAGE DOMINOS_USERS AS
  PROCEDURE INSERT_USER(USER_FIRST_NAME_IN IN T_USERS.USER_FIRST_NAME%TYPE, 
                        USER_LAST_NAME_IN IN T_USERS.USER_LAST_NAME%TYPE, 
                        USER_MIDDLE_NAME_IN IN T_USERS.USER_MIDDLE_NAME%TYPE DEFAULT NULL, 
                        USER_DATE_OF_BIRTH_IN IN T_USERS.USER_DATE_OF_BIRTH%TYPE, 
                        USER_GENDER_IN IN T_USERS.USER_GENDER%TYPE);
END DOMINOS_USERS;