DROP PACKAGE PKG_DOMINOS_USERS;
DROP PACKAGE PKG_DOMINOS_ACCOUNTS;
/

--------------------------------------------------------------------------------------USERS PACKAGE
CREATE OR REPLACE PACKAGE PKG_DOMINOS_USERS AS
  
  --PROCEDURES
  PROCEDURE INSERT_USER(USER_FIRST_NAME_IN IN T_USERS.USER_FIRST_NAME%TYPE, 
                        USER_LAST_NAME_IN IN T_USERS.USER_LAST_NAME%TYPE, 
                        USER_MIDDLE_NAME_IN IN T_USERS.USER_MIDDLE_NAME%TYPE DEFAULT NULL, 
                        USER_DATE_OF_BIRTH_IN IN T_USERS.USER_DATE_OF_BIRTH%TYPE, 
                        USER_GENDER_IN IN T_USERS.USER_GENDER%TYPE,
                        USER_EMAIL_IN IN T_USERS.USER_EMAIL%TYPE,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE);
  
  PROCEDURE DELETE_ALL_USERS;
  
  --FUNCTIONS
  FUNCTION GET_USER_BY_USER_EMAIL(USER_EMAIL_IN IN T_USERS.USER_EMAIL%TYPE)
  RETURN T_USERS.USER_ID%TYPE;
                        
END PKG_DOMINOS_USERS;
/

CREATE OR REPLACE PACKAGE BODY PKG_DOMINOS_USERS AS
  
  --PROCEDURES
  PROCEDURE INSERT_USER(USER_FIRST_NAME_IN IN T_USERS.USER_FIRST_NAME%TYPE, 
                        USER_LAST_NAME_IN IN T_USERS.USER_LAST_NAME%TYPE, 
                        USER_MIDDLE_NAME_IN IN T_USERS.USER_MIDDLE_NAME%TYPE DEFAULT NULL, 
                        USER_DATE_OF_BIRTH_IN IN T_USERS.USER_DATE_OF_BIRTH%TYPE, 
                        USER_GENDER_IN IN T_USERS.USER_GENDER%TYPE,
                        USER_EMAIL_IN IN T_USERS.USER_EMAIL%TYPE,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE)
  IS
  BEGIN
    INSERT INTO T_USERS(USER_FIRST_NAME, USER_LAST_NAME, USER_MIDDLE_NAME, USER_DATE_OF_BIRTH, USER_GENDER, USER_EMAIL)
    VALUES(USER_FIRST_NAME_IN, USER_LAST_NAME_IN, USER_MIDDLE_NAME_IN, USER_DATE_OF_BIRTH_IN, USER_GENDER_IN, USER_EMAIL_IN);
    IF IS_COMMIT_IN THEN
      COMMIT;
    END IF;  
  END INSERT_USER;
  
  PROCEDURE DELETE_ALL_USERS 
  IS
  BEGIN
    DELETE FROM T_USERS;
  END DELETE_ALL_USERS;
  
  --FUNCTIONS
  FUNCTION GET_USER_BY_USER_EMAIL(USER_EMAIL_IN IN T_USERS.USER_EMAIL%TYPE)
  RETURN T_USERS.USER_ID%TYPE
  IS
    L_RETURN_RESULT T_USERS.USER_ID%TYPE;
  BEGIN
    SELECT U.USER_ID INTO L_RETURN_RESULT
    FROM T_USERS U
    WHERE USER_EMAIL_IN IS NOT NULL AND U.USER_EMAIL = USER_EMAIL_IN;
    RETURN L_RETURN_RESULT;
  END GET_USER_BY_USER_EMAIL;
END PKG_DOMINOS_USERS;
/

--------------------------------------------------------------------------------------ACCOUNTS PACKAGE
CREATE OR REPLACE PACKAGE PKG_DOMINOS_ACCOUNTS AS

  --PROCEDURES
  PROCEDURE INSERT_ACCOUNT(ACCOUNT_USER_ID_IN IN T_ACCOUNTS.ACCOUNT_USER_ID%TYPE, 
                        ACCOUNT_USERNAME_IN IN T_ACCOUNTS.ACCOUNT_USERNAME%TYPE, 
                        ACCOUNT_PASSWORD_IN IN T_ACCOUNTS.ACCOUNT_PASSWORD%TYPE DEFAULT NULL,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE);
                        
  PROCEDURE DELETE_ALL_ACCOUNTS;
                        
END PKG_DOMINOS_ACCOUNTS;
/

CREATE OR REPLACE PACKAGE BODY PKG_DOMINOS_ACCOUNTS AS
  
  --PROCEDURES
  PROCEDURE INSERT_ACCOUNT(ACCOUNT_USER_ID_IN IN T_ACCOUNTS.ACCOUNT_USER_ID%TYPE, 
                        ACCOUNT_USERNAME_IN IN T_ACCOUNTS.ACCOUNT_USERNAME%TYPE, 
                        ACCOUNT_PASSWORD_IN IN T_ACCOUNTS.ACCOUNT_PASSWORD%TYPE DEFAULT NULL,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE)
  IS
  BEGIN
    INSERT INTO T_ACCOUNTS(ACCOUNT_USER_ID, ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
    VALUES(ACCOUNT_USER_ID_IN, ACCOUNT_USERNAME_IN, ACCOUNT_PASSWORD_IN);
    IF IS_COMMIT_IN THEN
      COMMIT;
    END IF;  
  END INSERT_ACCOUNT;
  
  PROCEDURE DELETE_ALL_ACCOUNTS
  IS
  BEGIN
    DELETE FROM T_ACCOUNTS;
  END DELETE_ALL_ACCOUNTS;
  
END PKG_DOMINOS_ACCOUNTS;
/

--------------------------------------------------------------------------------------GAMES PACKAGE
CREATE OR REPLACE PACKAGE PKG_DOMINOS_GAMES AS

  --PROCEDURES
  PROCEDURE INSERT_GAME(GAME_NAME_IN IN T_GAMES.GAME_NAME%TYPE, 
                        CREATED_BY_USER_ID_IN IN T_GAMES.CREATED_BY_USER_ID%TYPE, 
                        CREATED_TIMESTAMP_IN IN T_GAMES.CREATED_TIMESTAMP%TYPE DEFAULT NULL,
                        START_TIMESTAMP_IN IN T_GAMES.START_TIMESTAMP%TYPE DEFAULT NULL,
                        END_TIMESTAMP_IN IN T_GAMES.END_TIMESTAMP%TYPE DEFAULT NULL,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE);
                        
  PROCEDURE DELETE_ALL_GAMES;
  
  --FUNCTIONS
  FUNCTION GET_GAME_BY_GAME_NAME(GAME_NAME_IN IN T_GAMES.GAME_NAME%TYPE)
  RETURN T_GAMES.GAME_ID%TYPE;
                        
END PKG_DOMINOS_GAMES;
/

CREATE OR REPLACE PACKAGE BODY PKG_DOMINOS_GAMES AS

  --PROCEDURES
  PROCEDURE INSERT_GAME(GAME_NAME_IN IN T_GAMES.GAME_NAME%TYPE, 
                        CREATED_BY_USER_ID_IN IN T_GAMES.CREATED_BY_USER_ID%TYPE, 
                        CREATED_TIMESTAMP_IN IN T_GAMES.CREATED_TIMESTAMP%TYPE DEFAULT NULL,
                        START_TIMESTAMP_IN IN T_GAMES.START_TIMESTAMP%TYPE DEFAULT NULL,
                        END_TIMESTAMP_IN IN T_GAMES.END_TIMESTAMP%TYPE DEFAULT NULL,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE)
  IS
  BEGIN
    INSERT INTO T_GAMES(GAME_NAME, CREATED_BY_USER_ID, CREATED_TIMESTAMP, START_TIMESTAMP, END_TIMESTAMP)
    VALUES(GAME_NAME_IN, CREATED_BY_USER_ID_IN, CREATED_TIMESTAMP_IN, START_TIMESTAMP_IN, END_TIMESTAMP_IN);
    IF IS_COMMIT_IN THEN
      COMMIT;
    END IF;  
  END INSERT_GAME;
  
  PROCEDURE DELETE_ALL_GAMES
  IS
  BEGIN
    DELETE FROM T_GAMES;
  END DELETE_ALL_GAMES;
  
   --FUNCTIONS
  FUNCTION GET_GAME_BY_GAME_NAME(GAME_NAME_IN IN T_GAMES.GAME_NAME%TYPE)
  RETURN T_GAMES.GAME_ID%TYPE
  IS
    RESULT_RETURN T_GAMES.GAME_ID%TYPE;
  BEGIN
    SELECT G.GAME_ID INTO RESULT_RETURN
    FROM T_GAMES G
    WHERE G.GAME_NAME = GAME_NAME_IN;
    RETURN RESULT_RETURN;
  END GET_GAME_BY_GAME_NAME;
  
END PKG_DOMINOS_GAMES;
/

--------------------------------------------------------------------------------------GAMES_ATTENDEES PACKAGE
CREATE OR REPLACE PACKAGE PKG_DOMINOS_GAMES_ATTENDEES AS

  --PROCEDURES
  PROCEDURE INSERT_GAMES_ATTENDEES(GAME_ID_IN IN T_GAMES_ATTENDEES.GAME_ID%TYPE, 
                        USER_ID_IN IN T_GAMES_ATTENDEES.USER_ID%TYPE,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE);
                        
  PROCEDURE DELETE_ALL_GAMES_ATTENDEES;
                        
END PKG_DOMINOS_GAMES_ATTENDEES;
/

CREATE OR REPLACE PACKAGE BODY PKG_DOMINOS_GAMES_ATTENDEES AS

  --PROCEDURES
  PROCEDURE INSERT_GAMES_ATTENDEES(GAME_ID_IN IN T_GAMES_ATTENDEES.GAME_ID%TYPE, 
                        USER_ID_IN IN T_GAMES_ATTENDEES.USER_ID%TYPE,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE)
  IS
  BEGIN
    INSERT INTO T_GAMES_ATTENDEES(GAME_ID, USER_ID)
    VALUES(GAME_ID_IN, USER_ID_IN);
    IF IS_COMMIT_IN THEN
      COMMIT;
    END IF;  
  END INSERT_GAMES_ATTENDEES;
  
  PROCEDURE DELETE_ALL_GAMES_ATTENDEES
  IS
  BEGIN
    DELETE FROM T_GAMES_ATTENDEES;
  END DELETE_ALL_GAMES_ATTENDEES;
  
END PKG_DOMINOS_GAMES_ATTENDEES;
/
SHOW ERRORS;
