DROP PACKAGE PKG_DOMINOS_USERS;
DROP PACKAGE PKG_DOMINOS_ACCOUNTS;
/

CREATE OR REPLACE PACKAGE PKG_DOMINOS_USERS AS
  PROCEDURE INSERT_USER(USER_FIRST_NAME_IN IN T_USERS.USER_FIRST_NAME%TYPE, 
                        USER_LAST_NAME_IN IN T_USERS.USER_LAST_NAME%TYPE, 
                        USER_MIDDLE_NAME_IN IN T_USERS.USER_MIDDLE_NAME%TYPE DEFAULT NULL, 
                        USER_DATE_OF_BIRTH_IN IN T_USERS.USER_DATE_OF_BIRTH%TYPE, 
                        USER_GENDER_IN IN T_USERS.USER_GENDER%TYPE,
                        USER_EMAIL_IN IN T_USERS.USER_EMAIL%TYPE,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE);
  FUNCTION GET_USER_BY_USER_EMAIL(USER_EMAIL_IN IN T_USERS.USER_EMAIL%TYPE)
  RETURN T_USERS.USER_ID%TYPE;
                        
END PKG_DOMINOS_USERS;
/

CREATE OR REPLACE PACKAGE BODY PKG_DOMINOS_USERS AS
  PROCEDURE INSERT_USER(USER_FIRST_NAME_IN IN T_USERS.USER_FIRST_NAME%TYPE, 
                        USER_LAST_NAME_IN IN T_USERS.USER_LAST_NAME%TYPE, 
                        USER_MIDDLE_NAME_IN IN T_USERS.USER_MIDDLE_NAME%TYPE DEFAULT NULL, 
                        USER_DATE_OF_BIRTH_IN IN T_USERS.USER_DATE_OF_BIRTH%TYPE, 
                        USER_GENDER_IN IN T_USERS.USER_GENDER%TYPE,
                        USER_EMAIL_IN IN T_USERS.USER_EMAIL%TYPE,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE)
  IS
  BEGIN
    INSERT INTO T_USERS(USER_FIRST_NAME, USER_LAST_NAME, USER_MIDDLE_NAME, USER_DATE_OF_BIRTH, USER_GENDER, USER_EMAIL)
    VALUES(USER_FIRST_NAME_IN, USER_LAST_NAME_IN, USER_MIDDLE_NAME_IN, USER_DATE_OF_BIRTH_IN, USER_GENDER_IN, USER_EMAIL_IN);
    IF IS_COMMIT_IN THEN
      COMMIT;
    END IF;  
  END INSERT_USER;
  
  FUNCTION GET_USER_BY_USER_EMAIL(USER_EMAIL_IN IN T_USERS.USER_EMAIL%TYPE)
  RETURN T_USERS.USER_ID%TYPE
  IS
    L_RETURN_RESULT T_USERS.USER_ID%TYPE;
  BEGIN
    SELECT U.USER_ID INTO L_RETURN_RESULT
    FROM T_USERS U
    WHERE USER_EMAIL_IN IS NOT NULL AND U.USER_EMAIL = USER_EMAIL_IN;
    RETURN L_RETURN_RESULT;
  END GET_USER_BY_USER_EMAIL;
END PKG_DOMINOS_USERS;
/

CREATE OR REPLACE PACKAGE PKG_DOMINOS_ACCOUNTS AS
  PROCEDURE INSERT_ACCOUNT(ACCOUNT_USER_ID_IN IN T_ACCOUNTS.ACCOUNT_USER_ID%TYPE, 
                        ACCOUNT_USERNAME_IN IN T_ACCOUNTS.ACCOUNT_USERNAME%TYPE, 
                        ACCOUNT_PASSWORD_IN IN T_ACCOUNTS.ACCOUNT_PASSWORD%TYPE DEFAULT NULL,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE);
END PKG_DOMINOS_ACCOUNTS;
/

CREATE OR REPLACE PACKAGE BODY PKG_DOMINOS_ACCOUNTS AS
  PROCEDURE INSERT_ACCOUNT(ACCOUNT_USER_ID_IN IN T_ACCOUNTS.ACCOUNT_USER_ID%TYPE, 
                        ACCOUNT_USERNAME_IN IN T_ACCOUNTS.ACCOUNT_USERNAME%TYPE, 
                        ACCOUNT_PASSWORD_IN IN T_ACCOUNTS.ACCOUNT_PASSWORD%TYPE DEFAULT NULL,
                        IS_COMMIT_IN IN BOOLEAN DEFAULT TRUE)
  IS
  BEGIN
    INSERT INTO T_ACCOUNTS(ACCOUNT_USER_ID, ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
    VALUES(ACCOUNT_USER_ID_IN, ACCOUNT_USERNAME_IN, ACCOUNT_PASSWORD_IN);
    IF IS_COMMIT_IN THEN
      COMMIT;
    END IF;  
  END INSERT_ACCOUNT;
END PKG_DOMINOS_ACCOUNTS;
/
