SET SERVEROUTPUT ON;
DECLARE
  L_USER1_IVANOV T_USERS.USER_EMAIL%TYPE := 'IVANOV.IVAN1987@GMAIL.COM';
  L_USER2_PETROV T_USERS.USER_EMAIL%TYPE := 'PETROV.PETR1977@MAIL.RU';
  L_USER3_SIDOROV T_USERS.USER_EMAIL%TYPE := 'SIDOROV.SIDOR1989@MAIL.MD';
  L_USER4_VASILIEV T_USERS.USER_EMAIL%TYPE := 'VASILIEV.VASILII1982@GMAIL.COM';
  
  L_GAME_NAME T_GAMES.GAME_NAME%TYPE := 'FIRST_SIMPLE_GAME';
BEGIN
  --DELETE
  PKG_DOMINOS_GAMES_ATTENDEES.DELETE_ALL_GAMES_ATTENDEES;
  PKG_DOMINOS_GAMES.DELETE_ALL_GAMES;
  PKG_DOMINOS_ACCOUNTS.DELETE_ALL_ACCOUNTS;
  PKG_DOMINOS_USERS.DELETE_ALL_USERS;

  --ADD
  PKG_DOMINOS_USERS.INSERT_USER('IVANOV', 'IVAN', '', TO_DATE('20.06.1987', 'DD.MM.YYYY'), 'M', L_USER1_IVANOV, FALSE);
  PKG_DOMINOS_USERS.INSERT_USER('PETROV', 'PETR', NULL, TO_DATE('09.11.1977', 'DD.MM.YYYY'), 'M', L_USER2_PETROV);
  PKG_DOMINOS_USERS.INSERT_USER('SIDOROV', 'SIDOR', NULL, TO_DATE('01.01.1989', 'DD.MM.YYYY'), 'M', L_USER3_SIDOROV);
  PKG_DOMINOS_USERS.INSERT_USER('VASILIEV', 'VASILII', NULL, TO_DATE('18.12.1982', 'DD.MM.YYYY'), 'M', L_USER4_VASILIEV);
  
  PKG_DOMINOS_ACCOUNTS.INSERT_ACCOUNT(PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER1_IVANOV), 'IVANOV.IVAN1987', 'II1987');
  PKG_DOMINOS_ACCOUNTS.INSERT_ACCOUNT(PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER2_PETROV), 'PETROV.PETR1977', 'PP1977');
  PKG_DOMINOS_ACCOUNTS.INSERT_ACCOUNT(PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER3_SIDOROV), 'SIDOROV.SIDOR1989', 'SS1989');
  PKG_DOMINOS_ACCOUNTS.INSERT_ACCOUNT(PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER4_VASILIEV), 'VASILIEV.VASILII1982', 'VV1982');
  
  PKG_DOMINOS_GAMES.INSERT_GAME(L_GAME_NAME, PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER1_IVANOV));
  
  PKG_DOMINOS_GAMES_ATTENDEES.INSERT_GAMES_ATTENDEES(PKG_DOMINOS_GAMES.GET_GAME_BY_GAME_NAME(L_GAME_NAME), PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER1_IVANOV));
  PKG_DOMINOS_GAMES_ATTENDEES.INSERT_GAMES_ATTENDEES(PKG_DOMINOS_GAMES.GET_GAME_BY_GAME_NAME(L_GAME_NAME), PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER2_PETROV));
  PKG_DOMINOS_GAMES_ATTENDEES.INSERT_GAMES_ATTENDEES(PKG_DOMINOS_GAMES.GET_GAME_BY_GAME_NAME(L_GAME_NAME), PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER3_SIDOROV));
  PKG_DOMINOS_GAMES_ATTENDEES.INSERT_GAMES_ATTENDEES(PKG_DOMINOS_GAMES.GET_GAME_BY_GAME_NAME(L_GAME_NAME), PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER4_VASILIEV));
  
  SYS.DBMS_OUTPUT.PUT_LINE('RESULT = ' || PKG_DOMINOS_GAMES_ATTENDEES.GET_G_A_BY_G_NAME_AND_U_NAME(PKG_DOMINOS_GAMES.GET_GAME_BY_GAME_NAME(L_GAME_NAME), PKG_DOMINOS_USERS.GET_USER_BY_USER_EMAIL(L_USER1_IVANOV)));
  
END;