--------------------------------------------------------------------------------
SET SERVEROUTPUT ON;
DECLARE
BEGIN
  SELECT * FROM V_USER_ACCOUNTS;
  SELECT * FROM V_GAMES;
  SELECT * FROM V_USERS_CREATED_GAMES;
  SELECT * FROM V_GAMES_ATTENDEES;
  SELECT * FROM V_GAME_ATTENDEES_USERS;
  
END;

--------------------------------------------------------------------------------
SET SERVEROUTPUT ON;
DECLARE
  CUR_RANDOM_INTERATION INTEGER;
  DOMINO_COUNT INTEGER := PKG_DOMINOS_DOMINOS.GET_DOMINO_COUNT;
  
  FUNCTION GET_RANDOM
  RETURN INTEGER
  IS
    CUR_RANDOM INTEGER;
  BEGIN
    SELECT ROUND(SYS.DBMS_RANDOM.VALUE * 28) INTO CUR_RANDOM FROM DUAL;
    RETURN CUR_RANDOM;
  END;
    
BEGIN
  --SELECT SYS.DBMS_RANDOM.RANDOM FROM DUAL;
  FOR I IN 1 .. 100
  LOOP
    CUR_RANDOM_INTERATION := GET_RANDOM;
    IF CUR_RANDOM_INTERATION >= 27 THEN
      DBMS_OUTPUT.PUT_LINE(I || ' ----- ' || CUR_RANDOM_INTERATION);
    END IF;  
  END LOOP;
END;  

--------------------------------------------------------------------------------
SET SERVEROUTPUT ON;
DECLARE
  DOMINO T_DOMINOS%ROWTYPE;
BEGIN
  DOMINO := PKG_DOMINOS_DOMINOS.GET_RANDOM_DOMINO;
  DBMS_OUTPUT.PUT_LINE(DOMINO.DOMINO_LEFT_PIECE || '|' || DOMINO.DOMINO_RIGHT_PIECE);
END;