PROMPT --------------DROP TRIGGERS--------------;
DROP TRIGGER TRIGGER_AUDIT_LANGUAGES;
DROP TRIGGER TRIGGER_AUDIT_PART_OF_SPEECHES;
DROP TRIGGER TRIGGER_AUDIT_WORDS;
DROP TRIGGER TRIGGER_AUDIT_TRANSLATES;