PROMPT ----------------DROP PUBLIC SYNONYMS----------------------;
--DROP PUBLIC SYNONYMS
DROP PUBLIC SYNONYM SYN_T_LANGUAGES;
DROP PUBLIC SYNONYM SYN_V_LANGUAGES;
DROP PUBLIC SYNONYM SYN_PACKAGE_WORDS_LANGUAGES;

SHOW ERRORS;