PROMPT DROP USER USER_WORLD_DB;
--DROP USER
DROP USER USER_WORLD_DB CASCADE;

PROMPT DROP PROFILE PR_USER_WORLD_DB;
--DROP PROFILE
DROP PROFILE PR_USER_WORLD_DB;

/*PROMPT DROP ROLE ROLE_USER_WORLD_DB;
--DROP ROLE
DROP ROLE ROLE_USER_WORLD_DB;
*/
PROMPT DROP TABLESPACE TEMP_TBL_USER_WORLD_DB;
DROP TABLESPACE TEMP_TBL_USER_WORLD_DB;
--DROP TABLESPACE
DROP TABLESPACE TEMP_TBL_USER_WORLD_DB
INCLUDING CONTENTS CASCADE CONSTRAINTS;

PROMPT DROP TABLESPACE TBL_USER_WORLD_DB;
DROP TABLESPACE TBL_USER_WORLD_DB 
INCLUDING CONTENTS CASCADE CONSTRAINTS;

SHOW ERRORS;