CREATE OR REPLACE PROCEDURE INSERT_OPERATION(OPERATION_ID_IN IN T_C_OPERATIONS.OPERATION_ID%TYPE,
                                            OPERATION_NAME_IN IN T_C_OPERATIONS.OPERATION_NAME%TYPE) IS
BEGIN
  INSERT INTO T_C_OPERATIONS(OPERATION_ID, OPERATION_NAME) VALUES(OPERATION_ID_IN, OPERATION_NAME_IN);
END INSERT_OPERATION;
/