DECLARE
BEGIN
  INSERT_OPERATION(OPERATION_ID_IN => 1, OPERATION_NAME_IN => 'CREATE');
  INSERT_OPERATION(2, 'UPDATE');
  INSERT_OPERATION(3, 'DELETE');
END;

DECLARE
  L_T_C_OPERATIONS T_C_OPERATIONS%ROWTYPE;

  CURSOR ALL_OPERATIONS
    IS
    select * from t_c_operations;
BEGIN
  OPEN ALL_OPERATIONS;
  DBMS_OUTPUT.PUT_LINE('INSERTED DATA: ');
  LOOP
    FETCH ALL_OPERATIONS INTO L_T_C_OPERATIONS;
    EXIT WHEN ALL_OPERATIONS%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(L_T_C_OPERATIONS.OPERATION_ID || ' ' || L_T_C_OPERATIONS.OPERATION_NAME);
  END LOOP;
  CLOSE ALL_OPERATIONS;
END;