PROMPT --------------CREATE SEQUENCES--------------;
--CREATE SEQUENCES
CREATE SEQUENCE SEQ_LANGUAGES MINVALUE 1 MAXVALUE 99 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PART_OF_SPEECHES MINVALUE 1 MAXVALUE 50 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WORDS MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRANSLATES MINVALUE 1 MAXVALUE 999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT --------------CREATE TABLES--------------;
--CREATE TABLES
CREATE TABLE T_C_OPERATIONS(
  OPERATION_ID NUMBER(1,0) NOT NULL,
  OPERATION_NAME VARCHAR2(50 BYTE) NOT NULL,
  CONSTRAINT OPERATION_ID_PK PRIMARY KEY (OPERATION_ID),
  CONSTRAINT OPERATION_NAME_UNIQUE UNIQUE (OPERATION_NAME)
);

CREATE TABLE T_LANGUAGES
  (
    LANGUAGE_ID   NUMBER(10,0) DEFAULT SEQ_LANGUAGES.NEXTVAL NOT NULL ,
    LANGUAGE_NAME VARCHAR2(50 BYTE) NOT NULL ,
    CONSTRAINT LANGUAGE_ID_PK PRIMARY KEY (LANGUAGE_ID)
  );

CREATE TABLE T_PART_OF_SPEECHES
  (
    PART_OF_SPEECH_ID NUMBER(10,0) DEFAULT SEQ_PART_OF_SPEECHES.NEXTVAL NOT NULL ,
    PART_OF_SPEECH    VARCHAR2(50 BYTE) NOT NULL ,
    CONSTRAINT PART_OF_SPEECH_ID_PK PRIMARY KEY (PART_OF_SPEECH_ID)
  );

CREATE TABLE T_WORDS
  (
    WORD_ID           NUMBER(10,0) DEFAULT SEQ_WORDS.NEXTVAL NOT NULL ,
    WORD              VARCHAR2(50 BYTE) NOT NULL ,
    LANGUAGE_ID       NUMBER(10,0) NOT NULL ,
    PART_OF_SPEECH_ID NUMBER(10,0) NOT NULL ,
    CONSTRAINT WORD_ID_PK PRIMARY KEY (WORD_ID),
    CONSTRAINT T_W_LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES (LANGUAGE_ID) ,
    CONSTRAINT T_W_PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES (PART_OF_SPEECH_ID)
  );

CREATE TABLE T_TRANSLATES
  (
    TRANSLATE_ID NUMBER(10,0) DEFAULT SEQ_TRANSLATES.NEXTVAL NOT NULL ,
    WORD_ID_F    NUMBER(10,0) NOT NULL ,
    WORD_ID_S    NUMBER(10,0) NOT NULL ,
    CONSTRAINT TRANSLATE_ID_PK PRIMARY KEY (TRANSLATE_ID)
  );

--ALTER TABLES
ALTER TABLE T_TRANSLATES ADD CONSTRAINT T_TRANSLATES_WORD_ID_F_FK FOREIGN KEY (WORD_ID_F) REFERENCES T_WORDS (WORD_ID) ;
ALTER TABLE T_TRANSLATES ADD CONSTRAINT T_TRANSLATES_WORD_ID_S_FK FOREIGN KEY (WORD_ID_S) REFERENCES T_WORDS (WORD_ID) ;
  
PROMPT --------------CREATE AUDITED TABLES--------------;
CREATE TABLE AUDIT_LANGUAGES
  (
    LANGUAGE_ID   NUMBER(10,0) NOT NULL ,
    CREATED_DATE_TIME TIMESTAMP NULL ,
    UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
    OPERATION_ID NUMBER(1,0) NOT NULL,
    CONSTRAINT A_L_LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES (LANGUAGE_ID),
    CONSTRAINT A_L_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
  );
  
CREATE TABLE AUDIT_PART_OF_SPEECHES
  (
    PART_OF_SPEECH_ID   NUMBER(10,0) NOT NULL ,
    CREATED_DATE_TIME TIMESTAMP NULL ,
    UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
    OPERATION_ID NUMBER(1,0) NOT NULL,
    CONSTRAINT A_P_PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES (PART_OF_SPEECH_ID),
    CONSTRAINT A_P_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
  );
  
CREATE TABLE AUDIT_WORDS
  (
    WORD_ID   NUMBER(10,0) NOT NULL ,
    CREATED_DATE_TIME TIMESTAMP NULL ,
    UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
    OPERATION_ID NUMBER(1,0) NOT NULL,
    CONSTRAINT A_W_WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS (WORD_ID),
    CONSTRAINT A_W_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
  );
  
CREATE TABLE AUDIT_TRANSLATES
  (
    TRANSLATE_ID   NUMBER(10,0) NOT NULL ,
    CREATED_DATE_TIME TIMESTAMP NULL ,
    UPDATED_DATE_TIME TIMESTAMP NOT NULL ,
    OPERATION_ID NUMBER(1,0) NOT NULL,
    CONSTRAINT A_T_TRANSLATE_ID_FK FOREIGN KEY (TRANSLATE_ID) REFERENCES T_TRANSLATES (TRANSLATE_ID),
    CONSTRAINT A_T_OPERATION_ID_FK FOREIGN KEY (OPERATION_ID) REFERENCES T_C_OPERATIONS (OPERATION_ID)
  );

/*
--CREATE INDEXIS
CREATE INDEX IDX_LANGUAGE_ID ON T_LANGUAGES(LANGUAGE_ID);
CREATE INDEX IDX_PART_OF_SPEECH_ID ON T_PART_OF_SPEECHES(PART_OF_SPEECH_ID);
CREATE INDEX IDX_WORD_ID ON T_WORDS(WORD_ID);
CREATE INDEX IDX_TRANSLATE_ID ON T_TRANSLATES(TRANSLATE_ID);
*/

PROMPT --------------CREATE VIEWS--------------;
--CREATE VIEWIES
CREATE OR REPLACE VIEW V_LANGUAGES AS
  SELECT *
  FROM T_LANGUAGES;  

CREATE OR REPLACE VIEW V_PART_OF_SPEECHES AS
  SELECT *
  FROM T_PART_OF_SPEECHES;

CREATE OR REPLACE VIEW V_TRANSLATES AS
  SELECT *
  FROM T_TRANSLATES;

CREATE OR REPLACE VIEW V_WORDS AS
  SELECT *
  FROM T_WORDS;

PROMPT --------------CREATE AUDITED VIEWS--------------;
CREATE OR REPLACE VIEW V_AUDIT_LANGUAGES AS
  SELECT l.LANGUAGE_NAME, al.*
  FROM T_LANGUAGES l inner join AUDIT_LANGUAGES al on l.LANGUAGE_ID = al.LANGUAGE_ID;

CREATE OR REPLACE VIEW V_AUDIT_PART_OF_SPEECHES AS
  SELECT pos.PART_OF_SPEECH, apos.*
  FROM T_PART_OF_SPEECHES pos inner join AUDIT_PART_OF_SPEECHES apos on pos.PART_OF_SPEECH_ID = apos.PART_OF_SPEECH_ID ;
  
CREATE OR REPLACE VIEW V_AUDIT_TRANSLATES AS
  SELECT (SELECT W.WORD FROM T_WORDS W WHERE W.WORD_ID = T.WORD_ID_F) AS WORD_F, 
  (SELECT W.WORD FROM T_WORDS W WHERE W.WORD_ID = T.WORD_ID_S) AS WORD_S , AT.*
  FROM T_TRANSLATES T INNER JOIN AUDIT_TRANSLATES AT ON T.TRANSLATE_ID = AT.TRANSLATE_ID;

CREATE OR REPLACE VIEW V_AUDIT_WORDS AS
  SELECT W.WORD, AW.*
  FROM T_WORDS W INNER JOIN AUDIT_WORDS AW ON W.WORD_ID = AW.WORD_ID;