PROMPT -------------DROP VIEWS-------------;
--DROP VIEWIES
DROP VIEW V_AUDIT_LANGUAGES;
DROP VIEW V_AUDIT_PART_OF_SPEECHES;
DROP VIEW V_AUDIT_WORDS;
DROP VIEW V_AUDIT_TRANSLATES;

DROP VIEW V_LANGUAGES;
DROP VIEW V_PART_OF_SPEECHES;
DROP VIEW V_WORDS;
DROP VIEW V_TRANSLATES;

--DROP INDEXIS
/*DROP INDEX IDX_LANGUAGE_ID;
DROP INDEX IDX_PART_OF_SPEECH_ID;
DROP INDEX IDX_WORD_ID;
DROP INDEX IDX_TRANSLATE_ID;*/

PROMPT -------------DROP TABLES-------------;
--DROP TABLES
DROP TABLE T_C_OPERATIONS;

DROP TABLE AUDIT_TRANSLATES;
DROP TABLE AUDIT_WORDS;
DROP TABLE AUDIT_PART_OF_SPEECHES;
DROP TABLE AUDIT_LANGUAGES;

DROP TABLE T_TRANSLATES;
DROP TABLE T_WORDS;
DROP TABLE T_PART_OF_SPEECHES;
DROP TABLE T_LANGUAGES;

PROMPT -------------DROP SEQUENCES-------------;
--DROP SEQUENCES
DROP SEQUENCE SEQ_LANGUAGES;
DROP SEQUENCE SEQ_PART_OF_SPEECHES;
DROP SEQUENCE SEQ_WORDS;
DROP SEQUENCE SEQ_TRANSLATES;
DROP SEQUENCE SEQ_OPERATION;

SHOW ERRORS;