set SERVEROUTPUT ON;
DECLARE
  LANG_ENG_NAME T_LANGUAGES.LANGUAGE_NAME%TYPE := 'ENG';
  LANG_ENG_ID T_LANGUAGES.LANGUAGE_ID%TYPE;
  
--  LANGUAGE_ENG T_LANGUAGES%ROWTYPE;
  
BEGIN
--  dbms_output.put_line(LANGUAGE_ENG.LANGUAGE_NAME || ' before');
--  LANGUAGE_ENG.LANGUAGE_NAME := LANG_ENG_NAME;
--  dbms_output.put_line(LANGUAGE_ENG.LANGUAGE_NAME || ' after');
  PACKAGE_WORDS_LANGUAGES.DELETE_ALL_LANGUAGE;
  dbms_output.put_line('delete all!');
--  PACKAGE_WORDS_LANGUAGES.INSERT_LANGUAGE(LANGUAGE_NAME_IN => LANGUAGE_ENG.LANGUAGE_NAME);
--  dbms_output.put_line('insert!');
  /*PACKAGE_WORDS_LANGUAGES.SELECT_LANGUAGE_BY_NAME(LANG_MDL_NAME, LANG_MDL_ID);
  dbms_output.put_line('select by name, id = ' || LANG_MDL_ID);
  PACKAGE_WORDS_LANGUAGES.UPDATE_LANGUAGE('Moldova', LANG_MDL_ID);
  dbms_output.put_line('update!');
  PACKAGE_WORDS_LANGUAGES.SELECT_LANGUAGE_BY_ID(LANG_MDL_ID, LANG_MDL_NAME);
  dbms_output.put_line('select by id = ' || LANG_MDL_NAME);
  PACKAGE_WORDS_LANGUAGES.DELETE_LANGUAGE(LANG_MDL_NAME, LANG_MDL_ID);
  dbms_output.put_line('delete!');*/
END;