SET SERVEROUTPUT ON;
DECLARE
  LANG_ENG_NAME T_LANGUAGES.LANGUAGE_NAME%TYPE := 'ENG';
  LANG_ENG_ID T_LANGUAGES.LANGUAGE_ID%TYPE;
  
  LANGUAGE_ENG T_LANGUAGES%ROWTYPE;
  LANGUAGE_RT T_LANGUAGES%ROWTYPE;
  L_SYS_REFCURSOR SYS_REFCURSOR;
BEGIN
--  PACKAGE_WORDS_LANGUAGES.TRUNCATE_LANGUAGE;
  dbms_output.put_line(LANGUAGE_ENG.LANGUAGE_NAME || ' before');
  LANGUAGE_ENG.LANGUAGE_NAME := LANG_ENG_NAME;
  dbms_output.put_line(LANGUAGE_ENG.LANGUAGE_NAME || ' after');
  PACKAGE_WORDS_LANGUAGES.DELETE_ALL_LANGUAGE(DELETE_AUDIT_TABLE_IN => 1);
  dbms_output.put_line('delete all!');
  PACKAGE_WORDS_LANGUAGES.INSERT_LANGUAGE(LANGUAGE_NAME_IN => LANGUAGE_ENG.LANGUAGE_NAME);
  dbms_output.put_line('insert!');
  PACKAGE_WORDS_LANGUAGES.SELECT_LANGUAGE_BY_NAME(LANGUAGE_ENG.LANGUAGE_NAME, LANGUAGE_ENG.LANGUAGE_ID);
  dbms_output.put_line('select by name, id = ' || LANGUAGE_ENG.LANGUAGE_ID);
  PACKAGE_WORDS_LANGUAGES.SELECT_LANGUAGE_BY_ID(LANGUAGE_ENG.LANGUAGE_ID, LANGUAGE_ENG.LANGUAGE_NAME);
  dbms_output.put_line('select by id, name = ' || LANGUAGE_ENG.LANGUAGE_NAME);
  LANGUAGE_ENG.LANGUAGE_NAME := 'MDL';
  PACKAGE_WORDS_LANGUAGES.UPDATE_LANGUAGE(LANGUAGE_ENG.LANGUAGE_NAME, LANGUAGE_ENG.LANGUAGE_ID);
  dbms_output.put_line('update!');
  PACKAGE_WORDS_LANGUAGES.SELECT_LANGUAGE_BY_ID(LANGUAGE_ENG.LANGUAGE_ID, LANGUAGE_ENG.LANGUAGE_NAME);
  dbms_output.put_line('select by id, name = ' || LANGUAGE_ENG.LANGUAGE_NAME);
  
  dbms_output.put_line('-----BEGIN');
  PACKAGE_WORDS_LANGUAGES.GET_ALL_LANGUAGE(L_SYS_REFCURSOR);
  LOOP
    FETCH L_SYS_REFCURSOR INTO LANGUAGE_RT;
    EXIT WHEN L_SYS_REFCURSOR%NOTFOUND;
    dbms_output.put_line('LANGUAGE_ID = ' || LANGUAGE_RT.LANGUAGE_ID || ', LANGUAGE_NAME = ' || LANGUAGE_RT.LANGUAGE_NAME);
  END LOOP;
  dbms_output.put_line('-----END');
  
  PACKAGE_WORDS_LANGUAGES.DELETE_LANGUAGE(LANGUAGE_ENG.LANGUAGE_NAME, LANGUAGE_ENG.LANGUAGE_ID);
  dbms_output.put_line('delete!');
  LANGUAGE_ENG.LANGUAGE_ID := null;
  PACKAGE_WORDS_LANGUAGES.SELECT_LANGUAGE_BY_NAME(LANGUAGE_ENG.LANGUAGE_NAME, LANGUAGE_ENG.LANGUAGE_ID);
  IF LANGUAGE_ENG.LANGUAGE_ID IS NULL THEN
    dbms_output.put_line('select by name, id = IS NULL');
  END IF;  
END;

--------------------------------------------------------------------------------
DECLARE
  LANGUAGE_ENG T_LANGUAGES%ROWTYPE;
  LANGUAGE_RUS T_LANGUAGES%ROWTYPE;
  T_PART_OF_SPEECHES_NOUN T_PART_OF_SPEECHES%ROWTYPE;
  T_PART_OF_SPEECHES_PRONOUN T_PART_OF_SPEECHES%ROWTYPE;
  T_PART_OF_SPEECHES_ADJECTIVE T_PART_OF_SPEECHES%ROWTYPE;
  T_PART_OF_SPEECHES_VERB T_PART_OF_SPEECHES%ROWTYPE;
  T_PART_OF_SPEECHES_ADVERB T_PART_OF_SPEECHES%ROWTYPE;
  T_PART_OF_SPEECHES_PREPOSITION T_PART_OF_SPEECHES%ROWTYPE;
  T_PART_OF_SPEECHES_CONJUCTION T_PART_OF_SPEECHES%ROWTYPE;
  T_PART_OF_SPEECHES_INTERJECT T_PART_OF_SPEECHES%ROWTYPE;
  T_PART_OF_SPEECHES_ARTICLE T_PART_OF_SPEECHES%ROWTYPE;
  
BEGIN
  LANGUAGE_ENG.LANGUAGE_NAME := 'ENG';
  LANGUAGE_RUS.LANGUAGE_NAME := 'RUS';
  
  PACKAGE_WORDS_LANGUAGES.DELETE_ALL_LANGUAGE(DELETE_AUDIT_TABLE_IN => 1);
  dbms_output.put_line('delete all LANGUAGES!');
  PACKAGE_WORDS_LANGUAGES.INSERT_LANGUAGE(LANGUAGE_NAME_IN => LANGUAGE_ENG.LANGUAGE_NAME);
  dbms_output.put_line('INSERTED ENG LANGUAGE!');
  PACKAGE_WORDS_LANGUAGES.INSERT_LANGUAGE(LANGUAGE_NAME_IN => LANGUAGE_RUS.LANGUAGE_NAME);
  dbms_output.put_line('INSERTED RUS LANGUAGE!');
  
  
  T_PART_OF_SPEECHES_NOUN.PART_OF_SPEECH := 'NOUN';
  T_PART_OF_SPEECHES_PRONOUN.PART_OF_SPEECH := 'PRONOUN';
  T_PART_OF_SPEECHES_ADJECTIVE.PART_OF_SPEECH := 'ADJECTIVE';
  T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH := 'VERB';
  T_PART_OF_SPEECHES_ADVERB.PART_OF_SPEECH := 'ADVERB';
  T_PART_OF_SPEECHES_PREPOSITION.PART_OF_SPEECH := 'PREPOSITION';
  T_PART_OF_SPEECHES_CONJUCTION.PART_OF_SPEECH := 'CONJUCTION';
  T_PART_OF_SPEECHES_INTERJECT.PART_OF_SPEECH := 'INTERJECTION';
  T_PART_OF_SPEECHES_ARTICLE.PART_OF_SPEECH := 'ARTICLE';
  
  PACKAGE_WORDS_PART_OF_SPEECHES.DELETE_ALL_PART_OF_SPEECH(DELETE_AUDIT_TABLE_IN => 1);
  dbms_output.put_line('delete all PART_OF_SPEECHES!');  
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_NOUN.PART_OF_SPEECH);
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_PRONOUN.PART_OF_SPEECH);
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_ADJECTIVE.PART_OF_SPEECH);
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_VERB.PART_OF_SPEECH);
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_ADVERB.PART_OF_SPEECH);
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_PREPOSITION.PART_OF_SPEECH);
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_CONJUCTION.PART_OF_SPEECH);
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_INTERJECT.PART_OF_SPEECH);
  PACKAGE_WORDS_PART_OF_SPEECHES.INSERT_PART_OF_SPEECH(T_PART_OF_SPEECHES_ARTICLE.PART_OF_SPEECH);
  dbms_output.put_line('INSERTED ALL PART_OF_SPEECHES!');
  
END;