PROMPT -------------------CREATE OR REPLACE PUBLIC SYNONYM-------------------------------------
--CREATE OR REPLACE PUBLIC SYNONYM
CREATE OR REPLACE PUBLIC SYNONYM SYN_T_LANGUAGES FOR T_LANGUAGES;
CREATE OR REPLACE PUBLIC SYNONYM SYN_V_LANGUAGES FOR V_LANGUAGES;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PACKAGE_WORDS_LANGUAGES FOR PACKAGE_WORDS_LANGUAGES;

SHOW ERRORS;