--SEQUENCE
drop SEQUENCE SEQ_LANGUAGE;
drop SEQUENCE SEQ_WORD;
drop SEQUENCE SEQ_PART_OF_SPEECH;
drop SEQUENCE SEQ_USER;

CREATE SEQUENCE SEQ_LANGUAGE
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE SEQ_WORD
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE SEQ_PART_OF_SPEECH
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE SEQ_USER
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
CACHE 10;

--TABLE
drop TABLE T_USERS_WORDS;
drop TABLE T_TRANSLATES;
drop TABLE T_ACCOUNTS;
drop TABLE T_USERS;
drop TABLE T_WORDS;
drop TABLE T_PART_OF_SPEECHES;
drop TABLE T_LANGUAGES;

CREATE TABLE T_LANGUAGES(
  LANGUAGE_ID NUMBER(9) DEFAULT SEQ_LANGUAGE.nextval not null,
  LANGUAGE_NAME VARCHAR2(50) not null, 
  CONSTRAINT LANGUAGE_ID_PK PRIMARY KEY(LANGUAGE_ID)
);

CREATE TABLE T_PART_OF_SPEECHES(
  PART_OF_SPEECH_ID NUMBER(9) DEFAULT SEQ_PART_OF_SPEECH.nextval not null,
  PART_OF_SPEECH_NAME VARCHAR2(50) not null, 
  CONSTRAINT PART_OF_SPEECH_ID_PK PRIMARY KEY(PART_OF_SPEECH_ID)
);

CREATE TABLE T_WORDS(
  WORD_ID NUMBER(9) DEFAULT SEQ_WORD.nextval not null,
  WORD VARCHAR2(50) not null, 
  LANGUAGE_ID NUMBER(9) not null,
  PART_OF_SPEECH_ID NUMBER(9) not null,
  CONSTRAINT WORD_ID_PK PRIMARY KEY(WORD_ID),
  CONSTRAINT LANGUAGE_ID_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES(LANGUAGE_ID),
  CONSTRAINT PART_OF_SPEECH_ID_FK FOREIGN KEY (PART_OF_SPEECH_ID) REFERENCES T_PART_OF_SPEECHES(PART_OF_SPEECH_ID)
);

CREATE TABLE T_USERS(
  USER_ID NUMBER(9) DEFAULT SEQ_USER.nextval not null,
  USER_FIRSTNAME VARCHAR2(75) not null, 
  USER_LASTNAME VARCHAR2(75) not null, 
  USER_MIDDLENAME VARCHAR2(75) not null, 
  USER_GENDER VARCHAR2(1) not null,
  USER_EMAIL VARCHAR2(128) not null,
  USER_PHONE VARCHAR2(20) not null,
  USER_DATE_OF_BIRTH DATE not null,
  CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID)
);

CREATE TABLE T_ACCOUNTS(
  USER_ID NUMBER(9) not null,
  ACCOUNT_USERNAME VARCHAR2(50) not null,
  ACCOUNT_PASSWORD VARCHAR2(256) not null,
  CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES T_USERS(USER_ID)
);

CREATE TABLE T_TRANSLATES(
  WORD_ID NUMBER(9) not null,
  WORD_TRANSLATE_ID NUMBER(9) not null,
  CONSTRAINT WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS(WORD_ID),
  CONSTRAINT WORD_TRANSLATE_ID_FK FOREIGN KEY (WORD_TRANSLATE_ID) REFERENCES T_WORDS(WORD_ID)
);

CREATE TABLE T_USERS_WORDS(
  USER_ID NUMBER(9) not null,
  WORD_ID NUMBER(9) not null,
  IS_TRUE_ANSWER CHAR(1) not null,
  CONSTRAINT U_W_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES T_USERS(USER_ID),
  CONSTRAINT U_W_WORD_ID_FK FOREIGN KEY (WORD_ID) REFERENCES T_WORDS(WORD_ID)
);
